//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.	
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace MoneyGram.AgentConnect.DomainModel.Transaction
{
		[Serializable]
		public class SystemError
		{
			public DateTime TimeStamp { get; set; }
			public string ErrorCode { get; set; }
			public string ErrorString { get; set; }
			public string SubErrorCode { get; set; }
			public string DetailString { get; set; }
		}
		[Serializable]
		public class VariableReceiptTextInfo
		{
			public string ReceiptTextType { get; set; }
			public List<TextTranslationType> TextTranslation { get; set; }
		}
		[Serializable]
		public class TextTranslationType
		{
			public string LongLanguageCode { get; set; }
			public string TextTranslation { get; set; }
		}
		[Serializable]
		public class UCPResponseProfileType
		{
			public DateTime? DateOfBirth { get; set; }
			public List<UCPResponseEmailType> EmailAddress { get; set; }
			public List<IdentificationDocumentType> IdentificationDocument { get; set; }
			public List<NameType> Name { get; set; }
			public List<UCPResponsePhoneType> PhoneNumber { get; set; }
			public List<ConsumerProfileIdentifierType> ConsumerProfileIdentifier { get; set; }
			public List<RawAddressType> RawAddress { get; set; }
		}
		[Serializable]
		public class UCPResponseEmailType
		{
			public DateTime? BounceDate { get; set; }
			public string EmailAddress { get; set; }
			public DateTime? EndDate { get; set; }
			public DateTime? StartDate { get; set; }
			public string Status { get; set; }
			public bool? StronglyAuthenticated { get; set; }
			public string Type { get; set; }
			public List<NotificationPreferenceType> NotificationPreference { get; set; }
		}
		[Serializable]
		public class NotificationPreferenceType
		{
			public DateTime? EndDate { get; set; }
			public string Frequency { get; set; }
			public string Method { get; set; }
			public bool? OptIn { get; set; }
			public string OptOutReason { get; set; }
			public string PreferredLanguage { get; set; }
			public DateTime? StartDate { get; set; }
			public bool? StronglyAuthenticated { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class IdentificationDocumentType
		{
			public DateTime? EndDate { get; set; }
			public string ExpirationDay { get; set; }
			public string ExpirationMonth { get; set; }
			public string ExpirationYear { get; set; }
			public string IdIssuerAuthorityCode { get; set; }
			public string IdNumber { get; set; }
			public string IssueCity { get; set; }
			public string IssueCountryCode { get; set; }
			public string IssueCountrySubDivisionCode { get; set; }
			public string IssueDay { get; set; }
			public string IssueMonth { get; set; }
			public string IssueYear { get; set; }
			public DateTime? StartDate { get; set; }
			public bool? StronglyAuthenticated { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class NameType
		{
			public string FirstName { get; set; }
			public string LastName { get; set; }
		}
		[Serializable]
		public class UCPResponsePhoneType
		{
			public string CountryDialInNumber { get; set; }
			public DateTime? EndDate { get; set; }
			public bool? MobileFlag { get; set; }
			public string PhoneNumber { get; set; }
			public DateTime? StartDate { get; set; }
			public bool? StronglyAuthenticated { get; set; }
			public string Type { get; set; }
			public List<NotificationPreferenceType> NotificationPreference { get; set; }
		}
		[Serializable]
		public class ConsumerProfileIdentifierType
		{
			public string ProfileID { get; set; }
			public DateTime? StartDate { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class RawAddressType : BaseRawAddressType
		{
			public StandardizedAddressType StandardizedAddress { get; set; }
		}
		[Serializable]
		public class StandardizedAddressType : BaseRawAddressType
		{
			public string AddressCleansingScore { get; set; }
		}
		[Serializable]
		public class BaseRawAddressType
		{
			public string AddressLine1 { get; set; }
			public string AddressLine2 { get; set; }
			public string AddressLine3 { get; set; }
			public string AddressLine4 { get; set; }
			public string City { get; set; }
			public string CountryCode { get; set; }
			public string CountrySubDivisionCode { get; set; }
			public string County { get; set; }
			public string PostalCode { get; set; }
		}
		[Serializable]
		public class SubagentInfo
		{
			public int AgentID { get; set; }
			public int? SequenceNumber { get; set; }
			public string LegacyAgentID { get; set; }
			public string City { get; set; }
			public string BranchName { get; set; }
			public int AgentStatus { get; set; }
			public string StoreNumber { get; set; }
			public string AgentStoreName { get; set; }
		}
		[Serializable]
		public class StagedTransactionInfo
		{
			public SessionType MgiSessionType { get; set; }
			public string SenderFirstName { get; set; }
			public string SenderMiddleName { get; set; }
			public string SenderLastName { get; set; }
			public string SenderLastName2 { get; set; }
			public string SenderAddress { get; set; }
			public string SenderCity { get; set; }
			public string SenderCountrySubdivision { get; set; }
			public string SenderCountry { get; set; }
			public string SenderPostalCode { get; set; }
			public string SenderPhone { get; set; }
			public string MgiRewardsNumber { get; set; }
			public string ReceiverFirstName { get; set; }
			public string ReceiverMiddleName { get; set; }
			public string ReceiverLastName { get; set; }
			public string ReceiverLastName2 { get; set; }
			public string DestinationCountrySubdivision { get; set; }
			public string DestinationCountry { get; set; }
			public string BillerName { get; set; }
			public string BillerAccountNumber { get; set; }
			public string ConfirmationNumber { get; set; }
			public decimal SendAmount { get; set; }
			public string SendCurrency { get; set; }
		}
		[Serializable]
		public class RedirectInfo
		{
			public decimal? OriginalSendAmount { get; set; }
			public string OriginalSendCurrency { get; set; }
			public decimal? OriginalSendFee { get; set; }
			public decimal? OriginalExchangeRate { get; set; }
			public decimal? OriginalReceiveAmount { get; set; }
			public string OriginalReceiveCurrency { get; set; }
			public string OriginalReceiveCountry { get; set; }
			public decimal? NewSendFee { get; set; }
			public decimal? NewExchangeRate { get; set; }
			public decimal? NewReceiveAmount { get; set; }
			public string NewReceiveCurrency { get; set; }
			public decimal? FeeDifference { get; set; }
			public RedirectInfoRedirectType? RedirectType { get; set; }
		}
		[Serializable]
		public class PromotionLookupInfo
		{
			public string PromotionDiscountName { get; set; }
			public string CurrencyCode { get; set; }
			public decimal? PromotionDiscount { get; set; }
			public decimal? PromotionMaxDiscountAmount { get; set; }
			public string PromotionCategoryName { get; set; }
			public string PromotionName { get; set; }
			public int? PromotionId { get; set; }
			public string PromotionBeginDate { get; set; }
			public string PromotionEndDate { get; set; }
			public string PromotionCategoryBeginDate { get; set; }
			public string PromotionCategoryEndDate { get; set; }
		}
		[Serializable]
		public class TransactionDocumentContentType
		{
			public string Identifier { get; set; }
			public string ReferenceNumber { get; set; }
			public string MimeType { get; set; }
			public List<ImageItemType> ImageItems { get; set; }
		}
		[Serializable]
		public class ImageItemType
		{
			public string Label { get; set; }
			public List<Byte> Image { get; set; }
		}
		[Serializable]
		public class PartnerCreditType
		{
			public List<CreditLimitInfo> CreditLimitInfo { get; set; }
			public bool? GoodFundsAgentFlag { get; set; }
			public bool? DepositProofRequiredFlag { get; set; }
		}
		[Serializable]
		public class CreditLimitInfo
		{
			public string CreditLimitType { get; set; }
			public decimal? CreditLimitAmount { get; set; }
		}
		[Serializable]
		public class MoneyGramSendSummaryInfo
		{
			public decimal FaceAmount { get; set; }
			public decimal FeeAmount { get; set; }
			public decimal TotalAmount { get; set; }
			public string SendCurrency { get; set; }
			public string AgentNumber { get; set; }
			public string AgentName { get; set; }
		}
		[Serializable]
		public class MoneyGramSendWithTaxDetailInfo
		{
			public string ReferenceNumber { get; set; }
			public decimal FaceAmount { get; set; }
			public decimal FeeAmount { get; set; }
			public decimal TotalAmount { get; set; }
			public string SendCurrency { get; set; }
			public PaymentType PaymentType { get; set; }
			public string AgentName { get; set; }
			public decimal? TaxAmount { get; set; }
			public decimal? TaxPercentage { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailInfo
		{
			public string ReferenceNumber { get; set; }
			public decimal FaceAmount { get; set; }
			public decimal FeeAmount { get; set; }
			public decimal TotalAmount { get; set; }
			public string SendCurrency { get; set; }
			public string AgentNumber { get; set; }
			public PaymentType PaymentType { get; set; }
			public string AgentName { get; set; }
			public DateTime Time { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveSummaryInfo
		{
			public string AgentNumber { get; set; }
			public string AgentName { get; set; }
			public decimal? CashOrCheckAmount { get; set; }
			public decimal? OtherPayoutAmount { get; set; }
			public string ReceiveCurrency { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveDetailInfo
		{
			public DateTime Time { get; set; }
			public string ReferenceNumber { get; set; }
			public string ReceiverName { get; set; }
			public string CheckNumber { get; set; }
			public decimal ReceiveAmount { get; set; }
			public string AgentNumber { get; set; }
			public string PayoutType { get; set; }
			public string AgentName { get; set; }
			public string AccountNumber { get; set; }
			public string ReceiveCurrency { get; set; }
		}
		[Serializable]
		public class LoyaltyTranslationType
		{
			public string MessageId { get; set; }
			public string MessageText { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
		}
		[Serializable]
		public class LoyaltyProgramTypeTranslationType
		{
			public string ProgramType { get; set; }
			public string ProgramNameText { get; set; }
			public string ProgramDescText { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
		}
		[Serializable]
		public class LoyaltyCardTypeTranslationType
		{
			public string CardType { get; set; }
			public string MessageText { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
		}
		[Serializable]
		public class LevelInfo
		{
			public int LevelNumber { get; set; }
			public string LevelValue { get; set; }
			public string LevelAttributeLabel { get; set; }
			public string LevelAttributeTag { get; set; }
			public string LevelAttributeVal { get; set; }
		}
		[Serializable]
		public class LanguageTranslationType
		{
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
			public string DisplayName { get; set; }
		}
		[Serializable]
		public class IndustryTranslationType
		{
			public string IndustryId { get; set; }
			public string DisplayName { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
		}
		[Serializable]
		public class IndustryInfo
		{
			public string IndustryID { get; set; }
			public string IndustryName { get; set; }
		}
		[Serializable]
		public class FQDOTextTranslationType
		{
			public string ReceiveCountry { get; set; }
			public string ServiceOption { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ReceiveCurrency { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
			public string ServiceOptionDisplayName { get; set; }
			public string ServiceOptionDisplayDescription { get; set; }
		}
		[Serializable]
		public class ServiceOptionInfo
		{
			public string ServiceOption { get; set; }
			public string ReceiveCurrency { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ServiceOptionDisplayName { get; set; }
			public string ServiceOptionDisplayDescription { get; set; }
			public string ServiceOptionCategoryId { get; set; }
			public string ServiceOptionCategoryDisplayName { get; set; }
			public string LocalCurrency { get; set; }
			public bool IndicativeRateAvailable { get; set; }
		}
		[Serializable]
		public class DestinationCountryInfo
		{
			public string DestinationCountry { get; set; }
			public List<ServiceOptionInfo> ServiceOptionInfos { get; set; }
		}
		[Serializable]
		public class DepositAndProofInfo
		{
			public bool? MgiEmployeeAutoAccept { get; set; }
			public string DepositReferenceNumber { get; set; }
			public string DepositDate { get; set; }
			public string AnnouncementDate { get; set; }
			public decimal? AnnouncementAmount { get; set; }
			public string AnnouncementCurrencyCode { get; set; }
			public string PaymentTypeCode { get; set; }
			public string BankShortCode { get; set; }
			public string BankName { get; set; }
			public string AnnouncementRemarks { get; set; }
			public string AnnouncementStatus { get; set; }
			public string CustomerAccountSiteID { get; set; }
			public string AgentEmployeeID { get; set; }
		}
		[Serializable]
		public class DeliveryOptionTranslationType
		{
			public string ServiceOption { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
			public string DisplayName { get; set; }
		}
		[Serializable]
		public class CurrencyTranslationType
		{
			public string CurrencyCode { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
			public string DisplayName { get; set; }
		}
		[Serializable]
		public class CountryTranslationType
		{
			public string CountryCode { get; set; }
			public string LanguageCode { get; set; }
			public string LongLanguageCode { get; set; }
			public string DisplayName { get; set; }
		}
		[Serializable]
		public class ConsumerProfileSearchInfo
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public List<KeyValuePairType> CurrentValues { get; set; }
		}
		[Serializable]
		public class KeyValuePairType
		{
			public string InfoKey { get; set; }
			public string Value { get; set; }
		}
		[Serializable]
		public class PaymentTypeInfo
		{
			public string PaymentTypeCode { get; set; }
			public string PaymentTypeName { get; set; }
			public string PaymentTypeDisplayName { get; set; }
		}
		[Serializable]
		public class BankInfo
		{
			public string BankId { get; set; }
			public string BankShortCode { get; set; }
			public string BankName { get; set; }
			public string BankDisplayName { get; set; }
			public List<PaymentTypeInfo> PaymentType { get; set; }
		}
		[Serializable]
		public class AgentAddressType
		{
			public List<string> AgentAddress { get; set; }
		}
		[Serializable]
		public class CurrencyInfo
		{
			public string CurrencyCode { get; set; }
			public string CurrencyName { get; set; }
			public string CurrencyPrecision { get; set; }
		}
		[Serializable]
		public class SubdivisionInfo
		{
			public string CountrySubdivisionCode { get; set; }
			public string CountrySubdivisionName { get; set; }
		}
		[Serializable]
		public class CountrySubdivisionInfo
		{
			public string CountryCode { get; set; }
			public List<SubdivisionInfo> Subdivisions { get; set; }
		}
		[Serializable]
		public class CountryInfo
		{
			public string CountryCode { get; set; }
			public string CountryName { get; set; }
			public string BaseCurrency { get; set; }
			public List<string> LookupKeys { get; set; }
			public List<string> ReceiveCurrencies { get; set; }
			public List<string> SendCurrencies { get; set; }
			public List<string> CountryDialCodes { get; set; }
		}
		[Serializable]
		public class ConsumerProfileTransactionHistoryType
		{
			public List<KeyValuePairType> CurrentValues { get; set; }
		}
		[Serializable]
		public class AttributeType
		{
			public string AttributeLabel { get; set; }
			public string AttributeTag { get; set; }
			public string AttributeValue { get; set; }
		}
		[Serializable]
		public class HierarchyLevelInfo
		{
			public Int64 HierarchyLevelElementNumber { get; set; }
			public string HierarchyLevelValue { get; set; }
			public List<AttributeType> Attributes { get; set; }
		}
		[Serializable]
		public class GenericBusinessError
		{
			public string ErrorCode { get; set; }
			public string Message { get; set; }
			public string MessageShort { get; set; }
		}
		[Serializable]
		public class ErrorInfo
		{
			public string ErrorCode { get; set; }
			public List<TextTranslationType> ErrorMessages { get; set; }
			public bool RecoverableFlag { get; set; }
		}
		[Serializable]
		public class EstimatedReceiveAmountInfo
		{
			public decimal? ReceiveAmount { get; set; }
			public string ReceiveCurrency { get; set; }
			public bool ValidCurrencyIndicator { get; set; }
			public string DisplayPayoutCurrency { get; set; }
			public decimal? TotalReceiveFees { get; set; }
			public decimal? TotalReceiveTaxes { get; set; }
			public decimal? TotalReceiveAmount { get; set; }
			public bool ReceiveFeesAreEstimated { get; set; }
			public bool ReceiveTaxesAreEstimated { get; set; }
			public List<AmountInfo> DetailEstimatedReceiveAmounts { get; set; }
		}
		[Serializable]
		public class AmountInfo
		{
			public string AmountType { get; set; }
			public decimal? Amount { get; set; }
			public string AmountCurrency { get; set; }
		}
		[Serializable]
		public class FeeInfo
		{
			public decimal ValidReceiveAmount { get; set; }
			public string ValidReceiveCurrency { get; set; }
			public decimal ValidExchangeRate { get; set; }
			public decimal? EstimatedReceiveAmount { get; set; }
			public string EstimatedReceiveCurrency { get; set; }
			public decimal? EstimatedExchangeRate { get; set; }
			public decimal? DisplayExchangeRate { get; set; }
			public decimal TotalAmount { get; set; }
			public string DestinationCountry { get; set; }
			public string ServiceOption { get; set; }
			public bool ReceiveAmountAltered { get; set; }
			public decimal? SaLimitAvailable { get; set; }
			public bool RevisedInformationalFee { get; set; }
			public string ServiceOptionCategoryDisplayName { get; set; }
			public string ServiceOptionCategoryId { get; set; }
			public string ServiceOptionDisplayName { get; set; }
			public string ServiceOptionDisplayDescription { get; set; }
			public int? DisplayOrder { get; set; }
			public string RegAuthText { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ReceiveAgentName { get; set; }
			public string ReceiveAgentAbbreviation { get; set; }
			public string MgManaged { get; set; }
			public string DisclosureText { get; set; }
			public string MgiSessionID { get; set; }
			public bool SendAmountAltered { get; set; }
			public string AdditionalInfoText { get; set; }
			public List<PromotionInfo> PromotionInfos { get; set; }
			public SendAmountInfo SendAmounts { get; set; }
			public EstimatedReceiveAmountInfo ReceiveAmounts { get; set; }
			public ErrorInfo ErrorInfo { get; set; }
		}
		[Serializable]
		public class PromotionInfo
		{
			public string PromotionCode { get; set; }
			public string PromotionDiscountId { get; set; }
			public string PromotionCategoryId { get; set; }
			public decimal? PromotionDiscount { get; set; }
			public decimal? PromotionDiscountAmount { get; set; }
			public string PromotionErrorCode { get; set; }
			public List<TextTranslationType> PromotionErrorMessages { get; set; }
		}
		[Serializable]
		public class SendAmountInfo
		{
			public decimal? SendAmount { get; set; }
			public string SendCurrency { get; set; }
			public decimal? TotalSendFees { get; set; }
			public decimal? TotalDiscountAmount { get; set; }
			public decimal? TotalSendTaxes { get; set; }
			public decimal? TotalAmountToCollect { get; set; }
			public List<AmountInfo> DetailSendAmounts { get; set; }
		}
		[Serializable]
		public class CountryFeeInfo
		{
			public decimal? FeeAmount { get; set; }
			public decimal? SendAmount { get; set; }
			public string SendCurrency { get; set; }
			public decimal? ValidReceiveAmount { get; set; }
			public string ValidReceiveCurrency { get; set; }
			public decimal? ValidExchangeRate { get; set; }
			public bool? ValidIndicator { get; set; }
			public decimal? EstimatedReceiveAmount { get; set; }
			public string EstimatedReceiveCurrency { get; set; }
			public decimal? EstimatedExchangeRate { get; set; }
			public decimal? TotalAmount { get; set; }
			public string ReceiveCountry { get; set; }
			public string ServiceOption { get; set; }
			public bool? ReceiveAmountAltered { get; set; }
			public bool AmountExceededIndicator { get; set; }
			public decimal? MaxAmountAllowed { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ReceiveAgentName { get; set; }
			public string ReceiveAgentAbbreviation { get; set; }
		}
		[Serializable]
		public class StateRegulatorInfo
		{
			public string DfJurisdiction { get; set; }
			public string StateRegulatorURL { get; set; }
			public string StateRegulatorPhone { get; set; }
			public List<TextTranslationType> StateRegulatorName { get; set; }
		}
		[Serializable]
		public class DynamicContentAssemblyDetailsType
		{
			public string ResponseText { get; set; }
			public string ErrorCode { get; set; }
			public string MimeType { get; set; }
			public List<Byte> MimeData { get; set; }
		}
		[Serializable]
		public class ReceiptFormatDetailsType : DynamicContentAssemblyDetailsType
		{
			public string ReceiptText { get; set; }
			public string Md5CheckSum { get; set; }
			public string Version { get; set; }
			public string LongLanguageCode { get; set; }
			public List<string> AdditionalLanguages { get; set; }
		}
		[Serializable]
		public class DisclosureTextDetailsType : DynamicContentAssemblyDetailsType
		{
			public string Version { get; set; }
			public string LongLanguageCode { get; set; }
			public string DisclosureTextTag { get; set; }
		}
		[Serializable]
		public class StoreHourInfo
		{
			public DayOfWeekType DayOfWeek { get; set; }
			public DateTime? OpenTime { get; set; }
			public DateTime? CloseTime { get; set; }
			public bool Closed { get; set; }
		}
		[Serializable]
		public class AgentInfo
		{
			public string AgentName { get; set; }
			public string Address { get; set; }
			public string City { get; set; }
			public string CountrySubdivisionCode { get; set; }
			public bool? ReceiveCapability { get; set; }
			public bool? SendCapability { get; set; }
			public string AgentPhone { get; set; }
			public List<StoreHourInfo> StoreHours { get; set; }
		}
		[Serializable]
		public class ConsumerProfileIDInfo
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public DateTime? ConsumerProfileIDCreateDate { get; set; }
		}
		[Serializable]
		public class BillerLookupInfo
		{
			public List<KeyValuePairType> CurrentValues { get; set; }
		}
		[Serializable]
		public class ReceiverLookupInfo
		{
			public List<KeyValuePairType> CurrentValues { get; set; }
		}
		[Serializable]
		public class SenderLookupInfo
		{
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<ReceiverLookupInfo> ReceiverInfos { get; set; }
			public List<BillerLookupInfo> BillerInfos { get; set; }
		}
		[Serializable]
		public class CompletionReceiptType
		{
			public string ReceiptMimeType { get; set; }
			public string CharsetEncoding { get; set; }
			public List<ReceiptSegmentType> AgentReceiptMimeData { get; set; }
			public List<ReceiptSegmentType> ConsumerReceipt1MimeData { get; set; }
			public List<ReceiptSegmentType> ConsumerReceipt2MimeData { get; set; }
		}
		[Serializable]
		public class ReceiptSegmentType
		{
			public int? Sequence { get; set; }
			public List<Byte> MimeData { get; set; }
		}
		[Serializable]
		public class TimeZoneCorrectionType
		{
			public string TimeZoneId { get; set; }
			public int? Offset { get; set; }
			public int? DstSavings { get; set; }
			public int? StartMode { get; set; }
			public int? StartDay { get; set; }
			public int? StartMonth { get; set; }
			public int? StartDayOfWeek { get; set; }
			public int? StartTime { get; set; }
			public int? StartTimeMode { get; set; }
			public int? EndMode { get; set; }
			public int? EndDay { get; set; }
			public int? EndMonth { get; set; }
			public int? EndDayOfWeek { get; set; }
			public int? EndTime { get; set; }
			public int? EndTimeMode { get; set; }
		}
		[Serializable]
		public class ReceiveAmountInfo
		{
			public decimal? ReceiveAmount { get; set; }
			public string ReceiveCurrency { get; set; }
			public bool ValidCurrencyIndicator { get; set; }
			public string PayoutCurrency { get; set; }
			public decimal? TotalReceiveFees { get; set; }
			public decimal? TotalReceiveTaxes { get; set; }
			public decimal? TotalReceiveAmount { get; set; }
			public bool ReceiveFeesAreEstimated { get; set; }
			public bool ReceiveTaxesAreEstimated { get; set; }
			public List<AmountInfo> DetailReceiveAmounts { get; set; }
		}
		[Serializable]
		public class BillPaymentSummaryInfo
		{
			public ProductVariantType ProductVariant { get; set; }
			public decimal FaceAmount { get; set; }
			public decimal FeeAmount { get; set; }
			public decimal TotalAmount { get; set; }
			public string AgentNumber { get; set; }
			public string AgentName { get; set; }
		}
		[Serializable]
		public class BillPaymentDetailInfo
		{
			public string ReferenceNumber { get; set; }
			public ProductVariantType ProductVariant { get; set; }
			public decimal FaceAmount { get; set; }
			public decimal FeeAmount { get; set; }
			public decimal TotalAmount { get; set; }
			public bool? InfoFeeIndicator { get; set; }
			public decimal? ProcessingFee { get; set; }
			public string AgentNumber { get; set; }
			public PaymentType PaymentType { get; set; }
			public string AgentName { get; set; }
			public DateTime Date { get; set; }
			public TransactionStatusType Status { get; set; }
		}
		[Serializable]
		public class BillerInfo
		{
			public string ReceiveAgentID { get; set; }
			public string ReceiveCode { get; set; }
			public string InternationalBankAccountNumber { get; set; }
			public string BillerGroupID { get; set; }
			public string BillerGroupName { get; set; }
			public string BillerName { get; set; }
			public string Address1 { get; set; }
			public string Address2 { get; set; }
			public string Address3 { get; set; }
			public string BillerCity { get; set; }
			public string BillerState { get; set; }
			public string ServiceOfferingID { get; set; }
			public string ServiceOffering { get; set; }
			public string ServiceOfferingSecondary { get; set; }
			public string ServiceOfferingShort { get; set; }
			public string ServiceOfferingShortSecondary { get; set; }
			public List<string> IndustryID { get; set; }
			public string ExpectedPostingTimeFrame { get; set; }
			public string ExpectedPostingTimeFrameSecondary { get; set; }
			public string BillerNotes { get; set; }
			public string BillerNotesSecondary { get; set; }
			public string SecondaryLang { get; set; }
			public ProductVariantType ProductVariant { get; set; }
			public string BillerCutoffTime { get; set; }
			public string BillerWebsite { get; set; }
			public string BillerPhoneNumber { get; set; }
			public bool? MaskAccountNumber { get; set; }
			public bool? NationalBillerFlag { get; set; }
			public bool? UseStandardUBPFields { get; set; }
			public bool? AcctNumberNumericOnly { get; set; }
			public bool? SendFixedAmountFlag { get; set; }
			public bool? CancelWarnFlag { get; set; }
			public bool? RefundWarnFlag { get; set; }
			public bool? DoubleAcctNumberEntryFlag { get; set; }
			public decimal? MinimumFeeAmt { get; set; }
			public FeeType? FeeType { get; set; }
			public string ConsolidatorLocationId { get; set; }
			public string ConsolidatorName { get; set; }
			public string ClassOfTradeCode { get; set; }
			public bool? ExpeditedEligibleFlag { get; set; }
		}
		[Serializable]
		public class PreCompletionReceiptType
		{
			public string ReceiptMimeType { get; set; }
			public string CharsetEncoding { get; set; }
			public List<ReceiptSegmentType> Disclosure1MimeData { get; set; }
			public List<ReceiptSegmentType> Disclosure2MimeData { get; set; }
		}
		[Serializable]
		public class ChildField
		{
			public string FieldValue { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class InfoBase
		{
			public string InfoKey { get; set; }
			public string Label { get; set; }
			public string LabelStandAlone { get; set; }
			public int? DisplayOrder { get; set; }
			public string HelpTextShort { get; set; }
			public string HelpTextLong { get; set; }
			public string Documentation { get; set; }
		}
		[Serializable]
		public class FieldInfo : InfoBase
		{
			public bool? Display { get; set; }
			public DataType? DataType { get; set; }
			public EnumeratedTypeInfo Enumeration { get; set; }
			public string DisplayValue { get; set; }
		}
		[Serializable]
		public class EnumeratedTypeInfo
		{
			public string Name { get; set; }
			public List<EnumeratedIdentifierInfo> EnumeratedItems { get; set; }
		}
		[Serializable]
		public class EnumeratedIdentifierInfo
		{
			public string Identifier { get; set; }
			public string LabelShort { get; set; }
			public string Label { get; set; }
			public string HelpTextShort { get; set; }
			public string HelpTextLong { get; set; }
		}
		[Serializable]
		public class FieldToCollectInfo : FieldInfo
		{
			public bool? ReadOnly { get; set; }
			public bool? Required { get; set; }
			public bool? ChildFieldsKnown { get; set; }
			public Int64? FieldMin { get; set; }
			public Int64? FieldMax { get; set; }
			public string DefaultValue { get; set; }
			public string ValidationRegEx { get; set; }
			public string ExampleFormat { get; set; }
			public List<ChildField> ChildFields { get; set; }
			public string LookupDataSource { get; set; }
			public string LookupKey { get; set; }
		}
		[Serializable]
		public class CategoryInfo : InfoBase
		{
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class Payload
		{
			public bool DoCheckIn { get; set; }
			public DateTime TimeStamp { get; set; }
			public int Flags { get; set; }
		}
		[Serializable]
		public class BusinessError
		{
			public string ErrorCode { get; set; }
			public string Message { get; set; }
			public string SubErrorCode { get; set; }
			public string DetailString { get; set; }
			public string OffendingField { get; set; }
			public string ErrorCategory { get; set; }
			public string MessageShort { get; set; }
		}
		[Serializable]
		public class Response
		{
			public List<BusinessError> Errors { get; set; }
		}
		[Serializable]
		public class VersionManifestResponse : Response
		{
			public VersionManifestResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class VersionManifestResponsePayload : Payload
		{
			public Int64 ManifestSize { get; set; }
			public string ManifestURL { get; set; }
			public string VersionID { get; set; }
			public int UnitProfileID { get; set; }
		}
		[Serializable]
		public class VariableReceiptInfoResponse : Response
		{
			public VariableReceiptInfoResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class VariableReceiptInfoResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<VariableReceiptTextInfo> ReceiptText { get; set; }
		}
		[Serializable]
		public class TranslationsResponse : Response
		{
			public TranslationsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class TranslationsResponsePayload : Payload
		{
			public string TranslationsVersion { get; set; }
			public List<CountryTranslationType> CountryTranslations { get; set; }
			public List<DeliveryOptionTranslationType> DeliveryOptionTranslations { get; set; }
			public List<CurrencyTranslationType> CurrencyTranslations { get; set; }
			public List<FQDOTextTranslationType> FqdoTextTranslations { get; set; }
			public List<IndustryTranslationType> IndustryTranslations { get; set; }
			public List<LoyaltyTranslationType> LoyaltyTranslations { get; set; }
			public List<LoyaltyCardTypeTranslationType> LoyaltyCardTypeTranslations { get; set; }
			public List<LoyaltyProgramTypeTranslationType> LoyaltyProgramTypeTranslations { get; set; }
			public List<LanguageTranslationType> LanguageTranslations { get; set; }
		}
		[Serializable]
		public class TransactionLookupResponse : Response
		{
			public TransactionLookupResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class TransactionLookupResponsePayload : Payload
		{
			public string GAFVersionNumber { get; set; }
			public string MgiSessionID { get; set; }
			public TransactionStatusType TransactionStatus { get; set; }
			public RedirectInfo RedirectInfo { get; set; }
			public SendAmountInfo SendAmounts { get; set; }
			public ReceiveAmountInfo ReceiveAmounts { get; set; }
			public List<PromotionInfo> PromotionInfos { get; set; }
			public List<TextTranslationType> DisclosureTexts { get; set; }
			public List<TextTranslationType> ReceiveFeeDisclosureTexts { get; set; }
			public List<TextTranslationType> ReceiveTaxDisclosureTexts { get; set; }
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class SubagentsResponse : Response
		{
			public SubagentsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SubagentsResponsePayload : Payload
		{
			public List<SubagentInfo> Subagents { get; set; }
		}
		[Serializable]
		public class SendValidationResponse : Response
		{
			public SendValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SendValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public string Token { get; set; }
			public string CustomerReceiveNumber { get; set; }
			public string DisplayAccountID { get; set; }
			public string CustomerServiceMessage { get; set; }
			public string ReceiveAgentName { get; set; }
			public AgentAddressType ReceiveAgentAddress { get; set; }
			public string ReceiveAgentAbbreviation { get; set; }
			public decimal? ExchangeRateApplied { get; set; }
			public SendAmountInfo SendAmounts { get; set; }
			public ReceiveAmountInfo ReceiveAmounts { get; set; }
			public List<PromotionInfo> PromotionInfos { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public SendValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class SendValidationResponsePayloadReceiptInfo
		{
			public bool? ReceiveFeeDisclosureText { get; set; }
			public bool? ReceiveTaxDisclosureText { get; set; }
			public List<TextTranslationType> PromotionalMessages { get; set; }
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class SendReversalValidationResponse : Response
		{
			public SendReversalValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SendReversalValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public decimal? SendAmount { get; set; }
			public string SendCurrency { get; set; }
			public decimal? TotalSendFees { get; set; }
			public decimal? TotalSendTaxes { get; set; }
			public decimal? TotalReversalAmount { get; set; }
			public List<AmountInfo> DetailSendAmounts { get; set; }
			public SendReversalType? ReversalType { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public SendReversalValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class SendReversalValidationResponsePayloadReceiptInfo
		{
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class SearchStagedTransactionsResponse : Response
		{
			public SearchStagedTransactionsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SearchStagedTransactionsResponsePayload : Payload
		{
			public List<StagedTransactionInfo> StagedTransactionInfos { get; set; }
		}
		[Serializable]
		public class SearchConsumerProfilesResponse : Response
		{
			public SearchConsumerProfilesResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SearchConsumerProfilesResponsePayload : Payload
		{
			public string RequestGAFVersionNumber { get; set; }
			public string ResponseGAFVersionNumber { get; set; }
			public List<ConsumerProfileSearchInfo> ConsumerProfileSearchInfos { get; set; }
			public List<InfoBase> Infos { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
		}
		[Serializable]
		public class SaveTransactionDocumentResponse : Response
		{
			public SaveTransactionDocumentResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveTransactionDocumentResponsePayload : Payload
		{
			public string DocumentId { get; set; }
		}
		[Serializable]
		public class SaveSubagentsResponse : Response
		{
			public SaveSubagentsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveSubagentsResponsePayload : Payload
		{

		}
		[Serializable]
		public class SaveProfileResponse : Response
		{
			public SaveProfileResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveProfileResponsePayload : Payload
		{

		}
		[Serializable]
		public class SaveDebugDataResponse : Response
		{
			public SaveDebugDataResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveDebugDataResponsePayload : Payload
		{

		}
		[Serializable]
		public class SaveConsumerProfileDocumentResponse : Response
		{
			public SaveConsumerProfileDocumentResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveConsumerProfileDocumentResponsePayload : Payload
		{
			public string ImageReferenceId { get; set; }
		}
		[Serializable]
		public class SavePersonalIDImageResponse : Response
		{
			public SavePersonalIDImageResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SavePersonalIDImageResponsePayload : Payload
		{
			public string ImageReferenceId { get; set; }
		}
		[Serializable]
		public class SaveConsumerProfileImageResponse : Response
		{
			public SaveConsumerProfileImageResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class SaveConsumerProfileImageResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public string ImageReferenceID { get; set; }
		}
		[Serializable]
		public class RegisterHardTokenResponse : Response
		{
			public RegisterHardTokenResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class RegisterHardTokenResponsePayload : Payload
		{
			public bool RegistrationSuccessful { get; set; }
		}
		[Serializable]
		public class ReceiveValidationResponse : Response
		{
			public ReceiveValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ReceiveValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string Token { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public ReceiveValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class ReceiveValidationResponsePayloadReceiptInfo
		{
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class ReceiveReversalValidationResponse : Response
		{
			public ReceiveReversalValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ReceiveReversalValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public ReceiveReversalValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class ReceiveReversalValidationResponsePayloadReceiptInfo
		{
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class ReceiptsFormatDetailsResponse : Response
		{
			public ReceiptsFormatDetailsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ReceiptsFormatDetailsResponsePayload : Payload
		{
			public List<ReceiptFormatDetailsType> ReceiptFormatDetails { get; set; }
		}
		[Serializable]
		public class PromotionLookupByCodeResponse : Response
		{
			public PromotionLookupByCodeResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class PromotionLookupByCodeResponsePayload : Payload
		{
			public PromotionLookupInfo PromotionLookupInfo { get; set; }
		}
		[Serializable]
		public class ProfileResponse : Response
		{
			public ProfileResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ProfileResponsePayload : Payload
		{
			public List<ProfileItemType> ProfileItem { get; set; }
			public List<ProductProfileItemType> ProductProfileItem { get; set; }
			public List<EmployeeProfileItemType> EmployeeProfileItem { get; set; }
		}
		[Serializable]
		public class ProfileItemType
		{
			public int Index { get; set; }
			public string Key { get; set; }
			public string Value { get; set; }
		}
		[Serializable]
		public class ProductProfileItemType
		{
			public int Index { get; set; }
			public string Key { get; set; }
			public string Value { get; set; }
			public int ProductID { get; set; }
		}
		[Serializable]
		public class EmployeeProfileItemType
		{
			public int EmployeeID { get; set; }
			public string Key { get; set; }
			public int? Index { get; set; }
			public string Value { get; set; }
			public int ProductID { get; set; }
		}
		[Serializable]
		public class ProfileChangeResponse : Response
		{
			public ProfileChangeResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ProfileChangeResponsePayload : Payload
		{

		}
		[Serializable]
		public class OpenOTPLoginResponse : Response
		{
			public OpenOTPLoginResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class OpenOTPLoginResponsePayload : Payload
		{
			public bool LoginSuccessful { get; set; }
		}
		[Serializable]
		public class MoneyOrderTotalResponse : Response
		{
			public MoneyOrderTotalResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyOrderTotalResponsePayload : Payload
		{
			public string BatchID { get; set; }
		}
		[Serializable]
		public class MoneyGramSendSummaryReportResponse : Response
		{
			public MoneyGramSendSummaryReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyGramSendSummaryReportResponsePayload : Payload
		{
			public List<MoneyGramSendSummaryInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportWithTaxResponse : Response
		{
			public MoneyGramSendDetailReportWithTaxResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportWithTaxResponsePayload : Payload
		{
			public List<MoneyGramSendWithTaxDetailInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportResponse : Response
		{
			public MoneyGramSendDetailReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportResponsePayload : Payload
		{
			public List<MoneyGramSendDetailInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveSummaryReportResponse : Response
		{
			public MoneyGramReceiveSummaryReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveSummaryReportResponsePayload : Payload
		{
			public List<MoneyGramReceiveSummaryInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveDetailReportResponse : Response
		{
			public MoneyGramReceiveDetailReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveDetailReportResponsePayload : Payload
		{
			public List<MoneyGramReceiveDetailInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class InjectedInstructionResponse : Response
		{
			public InjectedInstructionResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class InjectedInstructionResponsePayload : Payload
		{

		}
		[Serializable]
		public class InitialSetupResponse : Response
		{
			public InitialSetupResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class InitialSetupResponsePayload : Payload
		{
			public string Token { get; set; }
			public int UnitProfileID { get; set; }
		}
		[Serializable]
		public class IndustryResponse : Response
		{
			public IndustryResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class IndustryResponsePayload : Payload
		{
			public List<IndustryInfo> IndustryInfoList { get; set; }
		}
		[Serializable]
		public class GetUCPByConsumerAttributesResponse : Response
		{
			public GetUCPByConsumerAttributesResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetUCPByConsumerAttributesResponsePayload : Payload
		{
			public UCPResponseProfileType ConsumerProfile { get; set; }
		}
		[Serializable]
		public class GetServiceOptionsResponse : Response
		{
			public GetServiceOptionsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetServiceOptionsResponsePayload : Payload
		{
			public List<DestinationCountryInfo> DestinationCountryInfos { get; set; }
		}
		[Serializable]
		public class GetReceiptForReprintResponse : Response
		{
			public GetReceiptForReprintResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetReceiptForReprintResponsePayload : Payload
		{
			public string ReceiptMimeType { get; set; }
			public List<Byte> AgentReceiptMimeData { get; set; }
			public List<Byte> ConsumerReceipt1MimeData { get; set; }
			public List<Byte> ConsumerReceipt2MimeData { get; set; }
		}
		[Serializable]
		public class GetProfileSenderResponse : Response
		{
			public GetProfileSenderResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetProfileSenderResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<InfoBase> Infos { get; set; }
			public List<KeyValuePairType[]> Receivers { get; set; }
			public List<KeyValuePairType[]> Billers { get; set; }
		}
		[Serializable]
		public class GetProfileReceiverResponse : Response
		{
			public GetProfileReceiverResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetProfileReceiverResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class GetProfileConsumerResponse : Response
		{
			public GetProfileConsumerResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetProfileConsumerResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileDocumentResponse : Response
		{
			public GetConsumerProfileDocumentResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileDocumentResponsePayload : Payload
		{
			public string MimeType { get; set; }
			public List<ImageItemType> ImageItems { get; set; }
		}
		[Serializable]
		public class GetPersonalIDImageResponse : Response
		{
			public GetPersonalIDImageResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetPersonalIDImageResponsePayload : Payload
		{
			public string MimeType { get; set; }
			public List<ImageItemType> ImageItems { get; set; }
		}
		[Serializable]
		public class GetEnumerationsResponse : Response
		{
			public GetEnumerationsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetEnumerationsResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<EnumeratedTypeInfo> Enumerations { get; set; }
		}
		[Serializable]
		public class GetDepositInformationResponse : Response
		{
			public GetDepositInformationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetDepositInformationResponsePayload : Payload
		{
			public decimal StartingARBalance { get; set; }
			public decimal DepositAndProofTotalAmount { get; set; }
			public decimal OutstandingTransactionTotalAmount { get; set; }
			public decimal CurrentCreditLimit { get; set; }
			public decimal OutstandingBalance { get; set; }
			public decimal AvailableCredit { get; set; }
			public List<DepositAndProofInfo> DepositAndProofInfo { get; set; }
			public PartnerCreditType PartnerCredit { get; set; }
		}
		[Serializable]
		public class GetDepositBankListResponse : Response
		{
			public GetDepositBankListResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetDepositBankListResponsePayload : Payload
		{
			public List<BankInfo> Bank { get; set; }
		}
		[Serializable]
		public class GetDebugDataResponse : Response
		{
			public GetDebugDataResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetDebugDataResponsePayload : Payload
		{
			public bool EndOfLog { get; set; }
			public Int64 CollectionEndTimestamp { get; set; }
			public string Length { get; set; }
			public string SequenceNumber { get; set; }
			public Object DebugData { get; set; }
		}
		[Serializable]
		public class GetCurrencyInfoResponse : Response
		{
			public GetCurrencyInfoResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetCurrencyInfoResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<CurrencyInfo> CurrencyInfos { get; set; }
		}
		[Serializable]
		public class GetCountrySubdivisionResponse : Response
		{
			public GetCountrySubdivisionResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetCountrySubdivisionResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<CountrySubdivisionInfo> CountrySubdivisionInfos { get; set; }
		}
		[Serializable]
		public class GetCountryInfoResponse : Response
		{
			public GetCountryInfoResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetCountryInfoResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<CountryInfo> CountryInfos { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileTransactionHistoryResponse : Response
		{
			public GetConsumerProfileTransactionHistoryResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileTransactionHistoryResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public int NumberOfRowsFound { get; set; }
			public List<ConsumerProfileTransactionHistoryType> Transactions { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class GetBroadcastMessagesResponse : Response
		{
			public GetBroadcastMessagesResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetBroadcastMessagesResponsePayload : Payload
		{
			public string Status { get; set; }
			public List<MessageInfo> MessageInfos { get; set; }
		}
		[Serializable]
		public class MessageInfo
		{
			public int? MessageId { get; set; }
			public int? MessageVersion { get; set; }
			public string MsgLanguageCode { get; set; }
			public string StartDate { get; set; }
			public string ExpiryDate { get; set; }
			public string SubjectMimeData { get; set; }
			public string ContentMimeData { get; set; }
		}
		[Serializable]
		public class GetBankDetailsResponse : Response
		{
			public GetBankDetailsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetBankDetailsResponsePayload : Payload
		{
			public List<KeyValuePairType> CurrentValues { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class GetBankDetailsByLevelResponse : Response
		{
			public GetBankDetailsByLevelResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetBankDetailsByLevelResponsePayload : Payload
		{
			public int HierarchyLevelNumber { get; set; }
			public string HierarchyLevelLabel { get; set; }
			public List<HierarchyLevelInfo> HierarchyLevelInfos { get; set; }
		}
		[Serializable]
		public class GetAllFieldsResponse : Response
		{
			public GetAllFieldsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetAllFieldsResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class GetAllErrorsResponse : Response
		{
			public GetAllErrorsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class GetAllErrorsResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<GenericBusinessError> DefinedErrors { get; set; }
		}
		[Serializable]
		public class FeeLookupResponse : Response
		{
			public FeeLookupResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class FeeLookupResponsePayload : Payload
		{
			public List<FeeInfo> FeeInfos { get; set; }
		}
		[Serializable]
		public class FeeLookupBySendCountryResponse : Response
		{
			public FeeLookupBySendCountryResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class FeeLookupBySendCountryResponsePayload : Payload
		{
			public List<CountryFeeInfo> CountryFeeInfo { get; set; }
		}
		[Serializable]
		public class DwProfileResponse : Response
		{
			public DwProfileResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DwProfileResponsePayload : Payload
		{
			public string Profile { get; set; }
		}
		[Serializable]
		public class DwPasswordResponse : Response
		{
			public DwPasswordResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DwPasswordResponsePayload : Payload
		{
			public bool Status { get; set; }
			public DwPasswordReasonCodeType ReasonCode { get; set; }
		}
		[Serializable]
		public class DwInitialSetupResponse : Response
		{
			public DwInitialSetupResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DwInitialSetupResponsePayload : Payload
		{
			public int UnitProfileID { get; set; }
			public string Token { get; set; }
			public string Profile { get; set; }
		}
		[Serializable]
		public class DoddFrankStateRegulatorInfoResponse : Response
		{
			public DoddFrankStateRegulatorInfoResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DoddFrankStateRegulatorInfoResponsePayload : Payload
		{
			public string Version { get; set; }
			public List<StateRegulatorInfo> StateRegulatorInfo { get; set; }
		}
		[Serializable]
		public class DisclosureTextDetailsResponse : Response
		{
			public DisclosureTextDetailsResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DisclosureTextDetailsResponsePayload : Payload
		{
			public List<DisclosureTextDetailsType> DisclosureTextDetails { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByZipResponse : Response
		{
			public DirectoryOfAgentsByZipResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByZipResponsePayload : Payload
		{
			public List<AgentInfo> AgentInfo { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByCityResponse : Response
		{
			public DirectoryOfAgentsByCityResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByCityResponsePayload : Payload
		{
			public List<AgentInfo> AgentInfo { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByAreaCodePrefixResponse : Response
		{
			public DirectoryOfAgentsByAreaCodePrefixResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByAreaCodePrefixResponsePayload : Payload
		{
			public List<AgentInfo> AgentInfo { get; set; }
		}
		[Serializable]
		public class DepositAnnouncementResponse : Response
		{
			public DepositAnnouncementResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class DepositAnnouncementResponsePayload : Payload
		{
			public string DepositAnnouncementID { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileSenderResponse : Response
		{
			public CreateOrUpdateProfileSenderResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileSenderResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public string CustomerServiceMessage { get; set; }
			public string ConsumerProfileID { get; set; }
			public List<ConsumerProfileIDInfo> ConsumerProfileIDs { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileReceiverResponse : Response
		{
			public CreateOrUpdateProfileReceiverResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileReceiverResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public string CustomerServiceMessage { get; set; }
			public string ConsumerProfileID { get; set; }
			public List<ConsumerProfileIDInfo> ConsumerProfileIDs { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileConsumerResponse : Response
		{
			public CreateOrUpdateProfileConsumerResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileConsumerResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public string GAFVersionNumber { get; set; }
			public string CustomerServiceMessage { get; set; }
			public string ConsumerProfileID { get; set; }
			public List<ConsumerProfileIDInfo> ConsumerProfileIDs { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
		}
		[Serializable]
		public class ConsumerHistoryLookupResponse : Response
		{
			public ConsumerHistoryLookupResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ConsumerHistoryLookupResponsePayload : Payload
		{
			public ConsumerHistoryLookupResponsePayloadSenderInfos SenderInfos { get; set; }
		}
		[Serializable]
		public class ConsumerHistoryLookupResponsePayloadSenderInfos
		{
			public List<SenderLookupInfo> SenderInfo { get; set; }
			public List<InfoBase> Infos { get; set; }
		}
		[Serializable]
		public class ConfirmTokenResponse : Response
		{
			public ConfirmTokenResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ConfirmTokenResponsePayload : Payload
		{
			public bool ProfileChanged { get; set; }
			public bool CodeTableChanged { get; set; }
		}
		[Serializable]
		public class ComplianceTransactionResponse : Response
		{
			public ComplianceTransactionResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class ComplianceTransactionResponsePayload : Payload
		{
			public bool ComplianceInfoRequired { get; set; }
			public CustomerComplianceInfo Cci { get; set; }
			public bool OfacStatus { get; set; }
			public string OfacSourceID { get; set; }
			public string BatchID { get; set; }
		}
		[Serializable]
		public class CustomerComplianceInfo
		{
			public CustomerComplianceTypeCodeType TypeCode { get; set; }
			public string OperatorName { get; set; }
			public DateTime? LocalDateTime { get; set; }
			public string EmployeeNumber { get; set; }
			public string Comments { get; set; }
			public int? Category { get; set; }
			public string OtherCategory { get; set; }
			public int? Character { get; set; }
			public string LastName { get; set; }
			public string FirstName { get; set; }
			public string MiddleInitial { get; set; }
			public string Address { get; set; }
			public string Address2 { get; set; }
			public string City { get; set; }
			public string State { get; set; }
			public string ZipCode { get; set; }
			public string Country { get; set; }
			public PhotoIdType? PhotoIdType { get; set; }
			public string PhotoIdNumber { get; set; }
			public string PhotoIdState { get; set; }
			public string PhotoIdCountry { get; set; }
			public DateTime? DateOfBirth { get; set; }
			public string PhoneNumber { get; set; }
			public string Occupation { get; set; }
			public LegalIdType? LegalIdType { get; set; }
			public string LegalIdNumber { get; set; }
			public string ThirdPartyDBA { get; set; }
			public string ThirdPartyLastName { get; set; }
			public string ThirdPartyFirstName { get; set; }
			public string ThirdPartyMiddleInitial { get; set; }
			public string ThirdPartyAddress { get; set; }
			public string ThirdPartyAddress2 { get; set; }
			public string ThirdPartyCity { get; set; }
			public string ThirdPartyState { get; set; }
			public string ThirdPartyZipCode { get; set; }
			public string ThirdPartyCountry { get; set; }
			public DateTime? ThirdPartyDOB { get; set; }
			public string ThirdPartyPhoneNumber { get; set; }
			public string ThirdPartyOccupation { get; set; }
			public LegalIdType? ThirdPartyLegalIdType { get; set; }
			public string ThirdPartyLegalIdNumber { get; set; }
		}
		[Serializable]
		public class CompleteSessionResponse : Response
		{
			public CompleteSessionResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CompleteSessionResponsePayload : Payload
		{
			public string ConfirmationNumber { get; set; }
			public string ReferenceNumber { get; set; }
			public string TransactionID { get; set; }
			public string ReferenceNumberText { get; set; }
			public string PartnerConfirmationNumber { get; set; }
			public string PartnerName { get; set; }
			public string ReceiveAgentAbbreviation { get; set; }
			public string FreePhoneCallPIN { get; set; }
			public string TollFreePhoneNumber { get; set; }
			public DateTime? ExpectedDateOfDelivery { get; set; }
			public DateTime TransactionDateTime { get; set; }
			public string AgentCheckAuthorizationNumber { get; set; }
			public CompletionReceiptType Receipts { get; set; }
			public CompleteSessionResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class CompleteSessionResponsePayloadReceiptInfo
		{
			public List<TextTranslationType> ReceiptTextInfos { get; set; }
		}
		[Serializable]
		public class CityListResponse : Response
		{
			public CityListResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CityListResponsePayload : Payload
		{
			public List<string> City { get; set; }
		}
		[Serializable]
		public class CheckInResponse : Response
		{
			public CheckInResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class CheckInResponsePayload : Payload
		{
			public string Token { get; set; }
			public TimeZoneCorrectionType TimeZoneCorrection { get; set; }
		}
		[Serializable]
		public class BPValidationResponse : Response
		{
			public BPValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class BPValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public string Token { get; set; }
			public string MgiRewardsNumber { get; set; }
			public ProductVariantType ProductVariant { get; set; }
			public string BillerCutoffTime { get; set; }
			public string BillerAddress { get; set; }
			public string BillerAddress2 { get; set; }
			public string BillerAddress3 { get; set; }
			public string BillerCity { get; set; }
			public string BillerState { get; set; }
			public string BillerPostalCode { get; set; }
			public string BillerPhone { get; set; }
			public string AgentTransactionId { get; set; }
			public string ServiceOfferingID { get; set; }
			public decimal? ProcessingFee { get; set; }
			public bool? InfoFeeIndicator { get; set; }
			public decimal? ExchangeRateApplied { get; set; }
			public SendAmountInfo SendAmounts { get; set; }
			public ReceiveAmountInfo ReceiveAmounts { get; set; }
			public List<PromotionInfo> PromotionInfos { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public BPValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class BPValidationResponsePayloadReceiptInfo
		{
			public string BillerWebsite { get; set; }
			public bool? PrintMGICustomerServiceNumber { get; set; }
			public List<TextTranslationType> ExpectedPostingTimeFrames { get; set; }
			public List<TextTranslationType> BillerNotes { get; set; }
			public List<TextTranslationType> ServiceOfferingDescriptions { get; set; }
			public List<TextTranslationType> CustomerTips { get; set; }
			public List<TextTranslationType> PromotionalMessages { get; set; }
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class BillPaymentSummaryReportResponse : Response
		{
			public BillPaymentSummaryReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class BillPaymentSummaryReportResponsePayload : Payload
		{
			public List<BillPaymentSummaryInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class BillPaymentDetailReportResponse : Response
		{
			public BillPaymentDetailReportResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class BillPaymentDetailReportResponsePayload : Payload
		{
			public List<BillPaymentDetailInfo> ReportInfo { get; set; }
		}
		[Serializable]
		public class BillerSearchResponse : Response
		{
			public BillerSearchResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class BillerSearchResponsePayload : Payload
		{
			public List<BillerInfo> BillerInfo { get; set; }
		}
		[Serializable]
		public class AmendValidationResponse : Response
		{
			public AmendValidationResponsePayload Payload { get; set; }
		}
		[Serializable]
		public class AmendValidationResponsePayload : Payload
		{
			public string MgiSessionID { get; set; }
			public bool ReadyForCommit { get; set; }
			public string GAFVersionNumber { get; set; }
			public List<InfoBase> FieldsToCollect { get; set; }
			public PreCompletionReceiptType Receipts { get; set; }
			public AmendValidationResponsePayloadReceiptInfo ReceiptInfo { get; set; }
		}
		[Serializable]
		public class AmendValidationResponsePayloadReceiptInfo
		{
			public List<TextTranslationType> DisclosureTexts { get; set; }
		}
		[Serializable]
		public class DocumentItemType
		{
			public string Label { get; set; }
			public string Image { get; set; }
		}
		[Serializable]
		public class SubagentProfileUpdateType
		{
			public string AgentID { get; set; }
			public int SequenceNumber { get; set; }
			public string ProfileItemName { get; set; }
			public string ProfileItemValue { get; set; }
		}
		[Serializable]
		public class ConsumerProfileDocumentContentType
		{
			public string Identifier { get; set; }
			public DateTime DocumentIssueDate { get; set; }
			public string MimeType { get; set; }
			public List<ImageItemType> ImageItems { get; set; }
		}
		[Serializable]
		public class PersonalIDImageContentType
		{
			public string Identifier { get; set; }
			public string PersonalIDChoice { get; set; }
			public string PersonalIDVerificationStr { get; set; }
			public string PersonalIDNumber { get; set; }
			public string MimeType { get; set; }
			public List<ImageItemType> ImageItems { get; set; }
		}
		[Serializable]
		public class ConsumerProfileImageContentType
		{
			public string Identifier { get; set; }
			public string MimeType { get; set; }
			public List<Byte> Image { get; set; }
		}
		[Serializable]
		public class ReceiptType
		{
			public string ReceiptText { get; set; }
			public string Md5CheckSum { get; set; }
			public string Version { get; set; }
			public string LongLanguageCode { get; set; }
			public string Province { get; set; }
			public List<string> AdditionalLanguages { get; set; }
		}
		[Serializable]
		public class UCPRequestPhoneType
		{
			public string PhoneNumber { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class UCPRequestEmailType
		{
			public string EmailAddress { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class UCPRequestProfileType
		{
			public DateTime? DateOfBirth { get; set; }
			public List<UCPRequestEmailType> EmailAddress { get; set; }
			public List<NameType> Name { get; set; }
			public List<UCPRequestPhoneType> PhoneNumber { get; set; }
			public List<RawAddressType> RawAddress { get; set; }
		}
		[Serializable]
		public class PropertyType
		{
			public string Name { get; set; }
			public string Value { get; set; }
		}
		[Serializable]
		public class CustomFieldsType
		{
			public PropertyType NameValue { get; set; }
		}
		[Serializable]
		public class DCATokenType
		{
			public string Key { get; set; }
			public string Value { get; set; }
		}
		[Serializable]
		public class VersionInfo
		{
			public string VersionType { get; set; }
			public string VersionLevel { get; set; }
		}
		[Serializable]
		public class MoneyOrderInfo
		{
			public MoneyOrderPrintStatusType PrintStatus { get; set; }
			public string MoAccountNumber { get; set; }
			public string DeviceID { get; set; }
			public string SerialNumber { get; set; }
			public decimal? ItemAmount { get; set; }
			public DateTime? DateTimePrinted { get; set; }
			public decimal? ItemFee { get; set; }
			public string PeriodNumber { get; set; }
			public string DocumentSequenceNbr { get; set; }
			public string DocumentType { get; set; }
			public string DispenserID { get; set; }
			public bool? VoidFlag { get; set; }
			public MoneyOrderVoidReasonCodeType? VoidReasonCode { get; set; }
			public string TaxID { get; set; }
			public string EmployeeID { get; set; }
			public string VendorNumber { get; set; }
			public bool? RemoteIssuanceFlag { get; set; }
			public string SaleIssuanceTag { get; set; }
			public decimal? DiscountPercentage { get; set; }
			public decimal? DiscountAmount { get; set; }
			public string AccountingStartDay { get; set; }
		}
		[Serializable]
		public class ReceiptImageContentType
		{
			public string Identifier { get; set; }
			public string MimeType { get; set; }
			public List<Byte> Image { get; set; }
		}
		[Serializable]
		public class Request
		{
			public int? UnitProfileID { get; set; }
			public string AgentID { get; set; }
			public string AgentSequence { get; set; }
			public string Language { get; set; }
			public string MgiSessionID { get; set; }
			public DateTime TimeStamp { get; set; }
			public string ClientSoftwareVersion { get; set; }
			public string PoeType { get; set; }
			public string ChannelType { get; set; }
			public string OperatorName { get; set; }
			public string TargetAudience { get; set; }
			public List<KeyValuePairType> PoeCapabilities { get; set; }
		}
		[Serializable]
		public class VersionManifestRequest : Request
		{

		}
		[Serializable]
		public class VariableReceiptInfoRequest : Request
		{
			public List<string> Languages { get; set; }
		}
		[Serializable]
		public class TranslationsRequest : Request
		{
			public string LanguageCodes { get; set; }
		}
		[Serializable]
		public class TransactionLookupRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string PurposeOfLookup { get; set; }
			public string ReferenceNumber { get; set; }
			public string ConfirmationNumber { get; set; }
			public string TransactionPin { get; set; }
		}
		[Serializable]
		public class SubagentsRequest : Request
		{

		}
		[Serializable]
		public class SendValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public bool TransactionStaging { get; set; }
			public decimal SendAmount { get; set; }
			public string SendCurrency { get; set; }
			public decimal? FeeAmount { get; set; }
			public List<string> PromoCodes { get; set; }
			public string DestinationCountry { get; set; }
			public string ServiceOption { get; set; }
			public string ReceiveCurrency { get; set; }
			public string ReceiveAgentID { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class SendReversalValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public decimal SendAmount { get; set; }
			public string SendCurrency { get; set; }
			public bool FeeRefund { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class SearchStagedTransactionsRequest : Request
		{
			public string MgiRewardsNumber { get; set; }
			public string SenderPhoneNumber { get; set; }
			public string SenderFirstName { get; set; }
			public string SenderLastName { get; set; }
			public string BillerAccountNumber { get; set; }
			public SessionType? MgiSessionType { get; set; }
			public bool ThisLocationOnly { get; set; }
			public string MaxRowsToReturn { get; set; }
			public bool ReturnFormFreeOnly { get; set; }
		}
		[Serializable]
		public class SearchConsumerProfilesRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
		}
		[Serializable]
		public class SaveTransactionDocumentRequest : Request
		{
			public SessionType SessionType { get; set; }
			public string ReferenceNumber { get; set; }
			public string SenderFirstName { get; set; }
			public string SenderMiddleName { get; set; }
			public string SenderLastName { get; set; }
			public string SenderLastName2 { get; set; }
			public string ReceiverFirstName { get; set; }
			public string ReceiverMiddleName { get; set; }
			public string ReceiverLastName { get; set; }
			public string ReceiverLastName2 { get; set; }
			public string Identifier { get; set; }
			public string MimeType { get; set; }
			public List<DocumentItemType> DocumentItems { get; set; }
		}
		[Serializable]
		public class SaveSubagentsRequest : Request
		{
			public List<SubagentProfileUpdateType> SubagentProfileUpdates { get; set; }
		}
		[Serializable]
		public class SaveProfileRequest : Request
		{
			public List<ProfileItemType> ProfileItems { get; set; }
			public List<ProductProfileItemType> ProductProfileItems { get; set; }
			public List<EmployeeProfileItemType> EmployeeProfileItems { get; set; }
		}
		[Serializable]
		public class SaveDebugDataRequest : Request
		{
			public bool EndOfLog { get; set; }
			public Int64 CollectionEndTimestamp { get; set; }
			public string Length { get; set; }
			public string SequenceNumber { get; set; }
			public string DebugData { get; set; }
		}
		[Serializable]
		public class SaveConsumerProfileDocumentRequest : Request
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public ConsumerProfileDocumentContentType ConsumerProfileDocument { get; set; }
		}
		[Serializable]
		public class SavePersonalIDImageRequest : Request
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public PersonalIDImageContentType PersonalIDImage { get; set; }
		}
		[Serializable]
		public class SaveConsumerProfileImageRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public ConsumerProfileImageContentType ConsumerProfileImage { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
		}
		[Serializable]
		public class RegisterHardTokenRequest : Request
		{
			public string LdapUserId { get; set; }
			public string HardToken { get; set; }
		}
		[Serializable]
		public class ReceiveValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public bool TransactionStaging { get; set; }
			public string ReceiveCurrency { get; set; }
			public decimal ReceiveAmount { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class ReceiveReversalValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public decimal ReceiveAmount { get; set; }
			public string ReceiveCurrency { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class ReceiptsFormatDetailsRequest : Request
		{
			public string PaperFormat { get; set; }
			public string MimeType { get; set; }
			public bool? DownloadAsAttachment { get; set; }
			public List<string> Languages { get; set; }
			public List<DCATokenType> DcaTokenValues { get; set; }
			public List<ReceiptType> ReceiptTypeValues { get; set; }
		}
		[Serializable]
		public class PromotionLookupByCodeRequest : Request
		{
			public string PromotionCode { get; set; }
		}
		[Serializable]
		public class ProfileRequest : Request
		{

		}
		[Serializable]
		public class ProfileChangeRequest : Request
		{
			public string Profile { get; set; }
		}
		[Serializable]
		public class OpenOTPLoginRequest : Request
		{
			public string LdapUserId { get; set; }
			public string Password { get; set; }
		}
		[Serializable]
		public class MoneyOrderTotalRequest : Request
		{
			public string BatchID { get; set; }
			public string BatchCount { get; set; }
			public decimal? BatchTotal { get; set; }
			public string MoAccountNumber { get; set; }
		}
		[Serializable]
		public class MoneyGramSendSummaryReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportWithTaxRequest : Request
		{
			public DateTime ActivityDate { get; set; }
		}
		[Serializable]
		public class MoneyGramSendDetailReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveSummaryReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
		}
		[Serializable]
		public class MoneyGramReceiveDetailReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
		}
		[Serializable]
		public class InjectedInstructionRequest : Request
		{
			public string PreviousPOETransactionID { get; set; }
			public string AdditionalTransactionInfo { get; set; }
		}
		[Serializable]
		public class InitialSetupRequest : Request
		{
			public string Password { get; set; }
			public string TimeZoneName { get; set; }
		}
		[Serializable]
		public class DwInitialSetupRequest : InitialSetupRequest
		{
			public string DeviceID { get; set; }
			public string ServiceTagNumber { get; set; }
		}
		[Serializable]
		public class IndustryRequest : Request
		{

		}
		[Serializable]
		public class GetUCPByConsumerAttributesRequest : Request
		{
			public string FunctionName { get; set; }
			public bool RepeatRequest { get; set; }
			public bool PlusEnrollmentFlag { get; set; }
			public string ResponseFilter { get; set; }
			public UCPRequestProfileType ConsumerProfile { get; set; }
			public string Id { get; set; }
			public string Type { get; set; }
		}
		[Serializable]
		public class GetServiceOptionsRequest : Request
		{
			public bool AgentAllowedOnly { get; set; }
			public string DestinationCountry { get; set; }
		}
		[Serializable]
		public class GetReceiptForReprintRequest : Request
		{
			public string ReferenceNumber { get; set; }
			public string ReceiptType { get; set; }
		}
		[Serializable]
		public class GetProfileSenderRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public int MaxReceiversToReturn { get; set; }
			public int MaxBillersToReturn { get; set; }
		}
		[Serializable]
		public class GetProfileReceiverRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
		}
		[Serializable]
		public class GetProfileConsumerRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileDocumentRequest : Request
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
		}
		[Serializable]
		public class GetPersonalIDImageRequest : Request
		{
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public string PersonalIDChoice { get; set; }
			public string PersonalIDVerificationStr { get; set; }
		}
		[Serializable]
		public class GetEnumerationsRequest : Request
		{
			public string CachedVersion { get; set; }
			public string EnumerationName { get; set; }
		}
		[Serializable]
		public class GetDepositInformationRequest : Request
		{
			public string MaxDepositsToReturn { get; set; }
		}
		[Serializable]
		public class GetDepositBankListRequest : Request
		{
			public string CountryCode { get; set; }
		}
		[Serializable]
		public class GetDebugDataRequest : Request
		{
			public DateTime? CurrentDate { get; set; }
			public int SequenceNumber { get; set; }
			public bool? NextTransmission { get; set; }
		}
		[Serializable]
		public class GetCurrencyInfoRequest : Request
		{
			public string Version { get; set; }
		}
		[Serializable]
		public class GetCountrySubdivisionRequest : Request
		{
			public string CachedVersion { get; set; }
			public string CountryCode { get; set; }
		}
		[Serializable]
		public class GetCountryInfoRequest : Request
		{
			public string CachedVersion { get; set; }
			public string LookupKey { get; set; }
		}
		[Serializable]
		public class GetConsumerProfileTransactionHistoryRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public DateTime? StartDate { get; set; }
			public DateTime? EndDate { get; set; }
			public int MaxRowsToReturn { get; set; }
			public string SortDateOrder { get; set; }
		}
		[Serializable]
		public class GetBroadcastMessagesRequest : Request
		{
			public string MsgLanguageCode { get; set; }
			public string OffsetGMT { get; set; }
			public List<MessageInfo> MessageInfos { get; set; }
			public List<CustomFieldsType> CustomFields { get; set; }
		}
		[Serializable]
		public class GetBankDetailsRequest : Request
		{
			public string CountryCode { get; set; }
			public string InfoKey { get; set; }
			public string Value { get; set; }
		}
		[Serializable]
		public class GetBankDetailsByLevelRequest : Request
		{
			public string CountryCode { get; set; }
			public int HierarchyLevelNumber { get; set; }
			public Int64? PreviousLevelElementNumber { get; set; }
		}
		[Serializable]
		public class GetAllFieldsRequest : Request
		{
			public string CachedVersion { get; set; }
			public string TransactionType { get; set; }
		}
		[Serializable]
		public class GetAllErrorsRequest : Request
		{
			public string CachedVersion { get; set; }
		}
		[Serializable]
		public class FeeLookupRequest : Request
		{
			public SessionType MgiSessionType { get; set; }
			public ProductVariantType? ProductVariant { get; set; }
			public decimal Item { get; set; }
			public ItemChoiceType1 ItemElementName { get; set; }
			public string DestinationCountry { get; set; }
			public string DestinationCountrySubdivisionCode { get; set; }
			public string SendCountry { get; set; }
			public string ServiceOption { get; set; }
			public string MgiRewardsNumber { get; set; }
			public string ReceiveCode { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ReceiveCurrency { get; set; }
			public string SendCurrency { get; set; }
			public string MgCustomerReceiveNumber { get; set; }
			public decimal? DefaultInformationalFee { get; set; }
			public string ServiceOfferingID { get; set; }
			public bool DefaultMaxFee { get; set; }
			public bool AllOptions { get; set; }
			public List<string> PromoCodes { get; set; }
		}
		[Serializable]
		public class FeeLookupBySendCountryRequest : Request
		{
			public SessionType MgiSessionType { get; set; }
			public ProductVariantType? ProductVariant { get; set; }
			public decimal Item { get; set; }
			public ItemChoiceType ItemElementName { get; set; }
			public string ReceiveCountry { get; set; }
			public string ServiceOption { get; set; }
			public string FreqCustCardNumber { get; set; }
			public string PromotionCode { get; set; }
			public string ReceiveCode { get; set; }
			public string IndicativeReceiveCurrency { get; set; }
			public bool? IssueFreqCustCard { get; set; }
			public string ReceiveAgentID { get; set; }
			public string ReceiveCurrency { get; set; }
			public string MgCustomerReceiveNumber { get; set; }
			public string SendCountry { get; set; }
			public string SendCurrency { get; set; }
			public bool AllOptions { get; set; }
		}
		[Serializable]
		public class DwProfileRequest : Request
		{

		}
		[Serializable]
		public class DwPasswordRequest : Request
		{
			public string EmployeeNumber { get; set; }
			public string CurrentPassword { get; set; }
			public string NewPassword { get; set; }
		}
		[Serializable]
		public class DoddFrankStateRegulatorInfoRequest : Request
		{
			public string DfJurisdiction { get; set; }
			public List<string> Languages { get; set; }
		}
		[Serializable]
		public class DisclosureTextDetailsRequest : Request
		{
			public string PaperFormat { get; set; }
			public string MimeType { get; set; }
			public bool? DownloadAsAttachment { get; set; }
			public List<string> Languages { get; set; }
			public List<DCATokenType> DcaTokenValues { get; set; }
			public string Province { get; set; }
			public string DestinationCountry { get; set; }
			public string DisclosureTextRevisionNumber { get; set; }
			public List<string> DcaTextTagValues { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByZipRequest : Request
		{
			public string ZipCode { get; set; }
			public string Country { get; set; }
			public string MaxRowsToReturn { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByCityRequest : Request
		{
			public string Country { get; set; }
			public string CountrySubdivisionCode { get; set; }
			public string City { get; set; }
			public string MaxRowsToReturn { get; set; }
		}
		[Serializable]
		public class DirectoryOfAgentsByAreaCodePrefixRequest : Request
		{
			public string AreaCodePrefix { get; set; }
			public string Country { get; set; }
			public string MaxRowsToReturn { get; set; }
		}
		[Serializable]
		public class DepositAnnouncementRequest : Request
		{
			public bool MgiEmployeeAutoAccept { get; set; }
			public string DepositReferenceNumber { get; set; }
			public DateTime DepositDate { get; set; }
			public DateTime AnnouncementDate { get; set; }
			public decimal AnnouncementAmount { get; set; }
			public string AnnouncementCurrencyCode { get; set; }
			public string PaymentTypeCode { get; set; }
			public string BankShortCode { get; set; }
			public string BankName { get; set; }
			public string AnnouncementRemarks { get; set; }
			public string AgentEmployeeID { get; set; }
			public List<Byte> ProofImage { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileSenderRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public string ConsumerProfileIDTypeToReturn { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileReceiverRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public string ConsumerProfileIDTypeToReturn { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
		}
		[Serializable]
		public class CreateOrUpdateProfileConsumerRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerProfileID { get; set; }
			public string ConsumerProfileIDType { get; set; }
			public string ConsumerProfileIDTypeToReturn { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
		}
		[Serializable]
		public class ConsumerHistoryLookupRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public string ConsumerPhone { get; set; }
			public string MgiRewardsNumber { get; set; }
			public string BillerAccountNumber { get; set; }
			public string AgentFrequentCustomerNumber { get; set; }
			public string MaxSendersToReturn { get; set; }
			public string MaxReceiversToReturn { get; set; }
			public SessionType MgiSessionType { get; set; }
		}
		[Serializable]
		public class ConfirmTokenRequest : Request
		{
			public string CodeTableVersion { get; set; }
			public List<VersionInfo> ClientTableVersions { get; set; }
		}
		[Serializable]
		public class ComplianceTransactionRequest : Request
		{
			public ComplianceTransactionRequestType RequestType { get; set; }
			public CustomerComplianceInfo Cci { get; set; }
			public string MgReferenceNumber { get; set; }
			public List<MoneyOrderInfo> MoneyOrder { get; set; }
		}
		[Serializable]
		public class CompleteSessionRequest : Request
		{
			public bool Commit { get; set; }
			public SessionType MgiSessionType { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class CityListRequest : Request
		{
			public string Country { get; set; }
			public string CountrySubdivisionCode { get; set; }
			public string City { get; set; }
			public string MaxRowsToReturn { get; set; }
		}
		[Serializable]
		public class CheckInRequest : Request
		{

		}
		[Serializable]
		public class BPValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public bool TransactionStaging { get; set; }
			public decimal SendAmount { get; set; }
			public decimal? FeeAmount { get; set; }
			public List<string> PromoCodes { get; set; }
			public string SendCurrency { get; set; }
			public string ReceiveCurrency { get; set; }
			public string DestinationCountry { get; set; }
			public ProductVariantType ProductVariant { get; set; }
			public string ServiceOfferingID { get; set; }
			public string ReceiveCode { get; set; }
			public string ReceiveAgentID { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public class BillPaymentSummaryReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
			public ProductVariantType? ProductVariant { get; set; }
		}
		[Serializable]
		public class BillPaymentDetailReportRequest : Request
		{
			public DateTime ActivityDate { get; set; }
			public ProductVariantType? ProductVariant { get; set; }
		}
		[Serializable]
		public class BillerSearchRequest : Request
		{
			public BillerSearchType SearchType { get; set; }
			public ProductVariantType? ProductVariant { get; set; }
			public string IndustryID { get; set; }
			public string ReceiveCode { get; set; }
			public string BillerName { get; set; }
			public string ReceiveAgentID { get; set; }
			public string BinNumber { get; set; }
			public decimal? DefaultInformationalFee { get; set; }
			public bool? DefaultMaxFee { get; set; }
			public string MaxRowsToReturn { get; set; }
		}
		[Serializable]
		public class AmendValidationRequest : Request
		{
			public string GAFVersionNumber { get; set; }
			public List<KeyValuePairType> FieldValues { get; set; }
			public List<string> VerifiedFields { get; set; }
			public string PrimaryReceiptLanguage { get; set; }
			public string SecondaryReceiptLanguage { get; set; }
			public List<ReceiptImageContentType> ReceiptImages { get; set; }
		}
		[Serializable]
		public enum SessionType
		{
			BP,
			SEND,
			RCV,
			SREV,
			RREV,
			AMD
		}
		[Serializable]
		public enum RedirectInfoRedirectType
		{
			CURRENCY_REDIRECT,
			COUNTRY_REDIRECT,
			COUNTRY_CURRENCY_REDIRECT
		}
		[Serializable]
		public enum PaymentType
		{
			CASH,
			CARD,
			CANCL
		}
		[Serializable]
		public enum DayOfWeekType
		{
			MON,
			TUE,
			WED,
			THU,
			FRI,
			MF,
			SS,
			SAT,
			SUN
		}
		[Serializable]
		public enum ProductVariantType
		{
			EP,
			PREPAY,
			UBP
		}
		[Serializable]
		public enum TransactionStatusType
		{
			AVAIL,
			CANCL,
			RECVD,
			REFND,
			AFR,
			UNCOMMITED,
			PRCSS
		}
		[Serializable]
		public enum FeeType
		{
			VARIABLE,
			EXACT,
			MINIMUM,
			NOT_FOUND
		}
		[Serializable]
		public enum DataType
		{
			boolean,
			@string,
			@int,
			@long,
			@decimal,
			date,
			datetime,
			time,
			@enum,
			gMonth,
			gYear,
			gDay
		}
		[Serializable]
		public enum SendReversalType
		{
			C,
			R
		}
		[Serializable]
		public enum DwPasswordReasonCodeType
		{
			PASSED,
			EMP_NOT_EXIST,
			IN_HIST,
			FORMAT_ERROR
		}
		[Serializable]
		public enum CustomerComplianceTypeCodeType
		{
			EMPTY_OR_NONE,
			OFAC_OR_AGGREGATION,
			MSL,
			RKL,
			CTR,
			SAR
		}
		[Serializable]
		public enum PhotoIdType
		{
			DRV,
			PAS,
			STA,
			GOV,
			ALN
		}
		[Serializable]
		public enum LegalIdType
		{
			SSN,
			INT,
			TAX,
			ALN
		}
		[Serializable]
		public enum MoneyOrderPrintStatusType
		{
			PROPOSED,
			NOT_ATTEMPTED,
			ATTEMPTED,
			CONFIRMED_PRINTED,
			CONFIRMED_NOT_PRINTED
		}
		[Serializable]
		public enum MoneyOrderVoidReasonCodeType
		{
			DISPENSER_ERROR,
			DEMO_MODE,
			TRAINING_MODE,
			TEST_VOID,
			VOID_REMAINING,
			LAST_ITEM
		}
		[Serializable]
		public enum ItemChoiceType1
		{
			amountExcludingFee,
			amountIncludingFee,
			receiveAmount
		}
		[Serializable]
		public enum ItemChoiceType
		{
			amountExcludingFee,
			amountIncludingFee,
			indicativeReceiveAmount,
			receiveAmount
		}
		[Serializable]
		public enum ComplianceTransactionRequestType
		{
			STANDALONE,
			PROPOSED,
			COMPLETED_WITH_CHANGES,
			COMPLETED_WITHOUT_CHANGES
		}
		[Serializable]
		public enum BillerSearchType
		{
			IND,
			CODE,
			NAME,
			ID,
			BIN
		}
		[Serializable]
		public enum EndpointConfiguration
		{
			AgentConnect
		}
}