//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcUpgradeTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcUpgradeTool.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using DOMAIN = {DomainNamespace};
        ///using SERVICE = MoneyGram.AgentConnect.Repository.AgentConnectService;
        ///
        ///namespace MoneyGram.AgentConnect.Rep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcDomainModelExtensionTemplate {
            get {
                return ResourceManager.GetString("AcDomainModelExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using MoneyGram.Common;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using SERVICE = MoneyGram.AgentConnect.Repository.AgentConnectService;
        ///using [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcDomainModelRequestExtensionTemplate {
            get {
                return ResourceManager.GetString("AcDomainModelRequestExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using AutoMapper;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq.Expressions;
        ///using AutoMapper.Configuration;
        ///
        ///namespace [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcMapperTemplate {
            get {
                return ResourceManager.GetString("AcMapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using DOMAIN = {DomainNamespace};
        ///using SERVICE = MoneyGram.AgentConnect.Repository.AgentConnectService;
        ///
        ///namespace MoneyGram.AgentConnect.Rep [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcServiceModelExtensionTemplate {
            get {
                return ResourceManager.GetString("AcServiceModelExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using AutoMapper;
        ///using AutoMapper.Configuration;
        ///
        ///namespace AwApi.EntityMapper
        ///{
        ///    public static class AwAgentConnectMapper
        ///    {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AwMapperTemplate {
            get {
                return ResourceManager.GetString("AwMapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System.Collections.Generic;
        ///using DOMAIN = {DomainNamespace};
        ///using VM = {VMNamespace};
        ///
        ///namespace {Namespace}
        ///{
        ///    public static cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AwModelExtensionTemplate {
            get {
                return ResourceManager.GetString("AwModelExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System.Collections.Generic;
        ///using DOMAIN = {DomainNamespace};
        ///using VM = {VMNamespace};
        ///
        ///namespace {Namespace}
        ///{
        ///    public static cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AwViewModelExtensionTemplate {
            get {
                return ResourceManager.GetString("AwViewModelExtensionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///using System;
        ///{usingStatements}
        ///namespace {namespace}
        ///{
        ///    [Serializable]
        ///    public {classType} {className}
        ///    {
        ///        {properties}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpModelTemplate {
            get {
                return ResourceManager.GetString("CSharpModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///	AcUpgradeTool &lt;wsdl path&gt; &lt;arguments&gt;
        ///
        ///Arguments:
        ///	&quot;/h&quot; or &quot;?&quot; for help.
        /// </summary>
        internal static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ////**
        /// * @ngdoc object
        /// * @typedef {ModelType}
        /// * @type Object
        /// * @name viewModels.value:{ModelType}
        /// *
        /// * @description
        /// * {ModelType} class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsModelTemplate {
            get {
                return ResourceManager.GetString("JsModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///(function (viewModels) {
        ///    &apos;use strict&apos;;
        ///
        ///    viewModels.constant(&apos;TransactionModelType&apos;, {
        ///        {ModelTypes}
        ///    });
        ///
        ///}(angular.modu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsModelTypeTemplate {
            get {
                return ResourceManager.GetString("JsModelTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///export enum {EnumType} {
        ///{EnumValues}}.
        /// </summary>
        internal static string TsEnumTemplate {
            get {
                return ResourceManager.GetString("TsEnumTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///{Imports}
        ///export class {ModelType} {
        ///{ModelProperties}}.
        /// </summary>
        internal static string TsModelTemplate {
            get {
                return ResourceManager.GetString("TsModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///export const TransactionModelType = {
        ///    {ModelTypes}
        ///};.
        /// </summary>
        internal static string TsModelTypeTemplate {
            get {
                return ResourceManager.GetString("TsModelTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        ///// ------------------------------------------------------------------------------
        ///import {module} from &apos;angular&apos;;
        ///
        ///{Imports}
        ///
        ///export default module(&apos;viewModels.transaction&apos;, [])
        ///    {ModuleItems}
        ///    .name;.
        /// </summary>
        internal static string TsModuleTemplate {
            get {
                return ResourceManager.GetString("TsModuleTemplate", resourceCulture);
            }
        }
    }
}
