//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyGram.AgentConnect.UpgradeUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoneyGram.AgentConnect.UpgradeUtility.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System.Threading.Tasks;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using MoneyGram.AgentConnect.DomainModel.Transaction;
        ///using MoneyGram.Ag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgentConnectDecoratorTemplate {
            get {
                return ResourceManager.GetString("AgentConnectDecoratorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public virtual {ResponseTypePascal} {MethodNamePascal}(Agent agent, {RequestTypePascal} {RequestTypeCamel})
        ///{
        ///	return AgentConnect.{MethodNamePascal}(agent, {RequestTypeCamel});
        ///}
        ///
        ///public virtual async Task&lt;{ResponseTypePascal}&gt; {MethodNamePascal}Async(Agent agent, {RequestTypePascal} {RequestTypeCamel})
        ///{
        ///	return await AgentConnect.{MethodNamePascal}Async(agent, {RequestTypeCamel});
        ///}.
        /// </summary>
        internal static string AgentConnectDecoratorTemplate_Method {
            get {
                return ResourceManager.GetString("AgentConnectDecoratorTemplate_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.	
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MoneyGram.AgentConnect.DomainModel.Transaction
        ///{
        ///{MODELS}
        ///}.
        /// </summary>
        internal static string AgentConnectModelsTemplate {
            get {
                return ResourceManager.GetString("AgentConnectModelsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Serializable]
        ///public class {CLASSNAME}
        ///{
        ///{PROPERTIES}
        ///}.
        /// </summary>
        internal static string AgentConnectModelsTemplate_Class {
            get {
                return ResourceManager.GetString("AgentConnectModelsTemplate_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Serializable]
        ///public enum {CLASSNAME}
        ///{
        ///{PROPERTIES}
        ///}.
        /// </summary>
        internal static string AgentConnectModelsTemplate_Enum {
            get {
                return ResourceManager.GetString("AgentConnectModelsTemplate_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System;
        ///using System.Threading.Tasks;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using MoneyGram.AgentConnect.EntityMapper;
        ///usi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgentConnectRepositoryTemplate {
            get {
                return ResourceManager.GetString("AgentConnectRepositoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public DOMAIN.{ResponseTypePascal} {MethodNamePascal}(Agent agent, DOMAIN.{RequestTypePascal} {RequestTypeCamel})
        ///{
        ///    Task&lt;DOMAIN.{ResponseTypePascal}&gt; callTask = Task.Run(() =&gt; this.{MethodNamePascal}Async(agent, {RequestTypeCamel}));
        ///    callTask.Wait();
        ///    return callTask.Result;
        ///}
        ///
        ///public async Task&lt;DOMAIN.{ResponseTypePascal}&gt; {MethodNamePascal}Async(Agent agent, DOMAIN.{RequestTypePascal} {RequestTypeCamel})
        ///{
        ///    agent.ThrowIfNull(nameof(agent));
        ///    {RequestTypeCamel}.ThrowIfNull(nameof [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AgentConnectRepositoryTemplate_Method {
            get {
                return ResourceManager.GetString("AgentConnectRepositoryTemplate_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using DOMAIN = MoneyGram.AgentConn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DomainToServiceExtensionsTemplate {
            get {
                return ResourceManager.GetString("DomainToServiceExtensionsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static SERVICE.{NAME} ToService(DOMAIN.{NAME} {NAME_CAMEL}, Agent agent)
        ///{
        ///	var serviceModel = new SERVICE.{NAME} {
        ///{PROPERTIES}
        ///	};
        ///
        ///	DomainTransformExtensions.NullifyWhiteSpaceStrings(serviceModel);
        ///
        ///	return serviceModel;
        ///}.
        /// </summary>
        internal static string DomainToServiceExtensionsTemplate_Extension {
            get {
                return ResourceManager.GetString("DomainToServiceExtensionsTemplate_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System.Threading.Tasks;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using MoneyGram.AgentConnect.DomainModel.Transaction;
        ///
        ///namespace MoneyG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IAgentConnectTemplate {
            get {
                return ResourceManager.GetString("IAgentConnectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using MoneyGram.AgentConnect.DomainModel;
        ///using DOMAIN = MoneyGram.AgentConn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ServiceToDomainExtensionsTemplate {
            get {
                return ResourceManager.GetString("ServiceToDomainExtensionsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static SERVICE.{NAME} ToService(DOMAIN.{NAME} {NAME_CAMEL}, Agent agent)
        ///{
        ///	var serviceModel = new SERVICE.{NAME} {
        ///{PROPERTIES}
        ///	};
        ///
        ///	DomainTransformExtensions.NullifyWhiteSpaceStrings(serviceModel);
        ///
        ///	return serviceModel;
        ///}.
        /// </summary>
        internal static string ServiceToDomainExtensionsTemplate_Extension {
            get {
                return ResourceManager.GetString("ServiceToDomainExtensionsTemplate_Extension", resourceCulture);
            }
        }
    }
}
